### ISSUE TITLE
内补采样的情况下预采样图片输入应该是必选不是可选，不然会报错

### ISSUE THREAD

**Issue by 807502278** [yolain/ComfyUI-Easy-Use#114]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/46019416/9334ff10-58b5-4dd3-acb2-538fb878ed8b)
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1_new\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\ComfyUI-aki-v1_new\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\ComfyUI-aki-v1_new\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\ComfyUI-aki-v1_new\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3471, in run
    t = vae.encode(pixels)
  File "D:\AI\ComfyUI-aki-v1_new\comfy\sd.py", line 313, in encode
    batch_number = int(free_memory / memory_used)
ZeroDivisionError: division by zero

**Comment by yolain** [comment]
是必选呢，我没办法判断呢 这是个通用的节点，大多数情况都是为可选的状态呢
