### ISSUE TITLE
1.5的inpaint pipeline, 完全和fooocus没关系，怎么easyloader一加载就报fooocus的错

### ISSUE THREAD

**Issue by deepfree2023** [yolain/ComfyUI-Easy-Use#117]
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 915, in adv_pipeloader
    return fullLoader.adv_pipeloader(self, ckpt_name, 'Default', vae_name, clip_skip,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 775, in adv_pipeloader
    positive_embeddings_final, positive_wildcard_prompt, model, clip = prompt_to_cond('positive', model, clip, clip_skip, pipe_lora_stack, positive, positive_token_normalization, positive_weight_interpretation, a1111_prompt_style, my_unique_id, prompt, easyCache)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\conditioning.py", line 23, in prompt_to_cond
    return (advanced_encode(clipped, text, prompt_token_normalization,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\adv_encode.py", line 315, in advanced_encode
    embeddings_final, pooled = advanced_encode_from_tokens(tokenized['l'],
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\adv_encode.py", line 200, in advanced_encode_from_tokens
    weighted_emb, pooled_base = encode_func(weighted_tokens)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\adv_encode.py", line 318, in <lambda>
    lambda x: (clip.encode_from_tokens({'l': x}), None),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 135, in encode_from_tokens
    self.load_model()
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 155, in load_model
    model_management.load_model_gpu(self.patcher)
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 451, in load_model_gpu
    return load_models_gpu([model])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 445, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 304, in model_load
    raise e
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 300, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to, patch_weights=load_weights)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 247, in patch_model
    self.patch_weight_to_device(key, device_to)
  File "F:\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 228, in patch_weight_to_device
    out_weight = self.calculate_weight(self.patches[key], temp_weight, key).to(weight.dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\fooocus.py", line 64, in calculate_weight_patched
    return self.original_calculate_weight(self, remaining, weight, key)

InpaintWorker.calculate_weight_patched() takes 4 positional arguments but 5 were given

**Comment by deepfree2023** [comment]
最新代码已修复
