### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by chookg** [yolain/ComfyUI-Easy-Use#127]
```
TypeError: Cannot read properties of undefined (reading 'type')
    at SetNode.onConnectionsChange (http://127.0.0.1:8188/extensions/ComfyUI-Easy-Use/js/getset.js:58:60)
    at LGraphNode.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2504:11)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2240:26)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1323:22)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:53:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1767:15)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/core/undoRedo.js:25:12)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/ComfyUI-Manager/components-manager.js:771:9)
```

![屏幕截图 2024-04-08 234350](https://github.com/yolain/ComfyUI-Easy-Use/assets/10023788/bdd874ac-e8d0-49e5-b37d-61d0df16154d)

**Comment by yolain** [comment]
一般是和set连接前的那个节点有关系呢。

**Comment by chookg** [comment]
https://github.com/SeargeDP/SeargeSDXL/pull/140/commits/9d11b6dcf4ae8ed3a4060b80ed29098f9f30b618

**Comment by Sheng-Charles** [comment]
同样的问题
```
Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at SetNode.onConnectionsChange (http://172.16.112.129:9999/extensions/ComfyUI-Easy-Use/js/getset.js:57:60)
    at LGraphNode.configure (http://172.16.112.129:9999/lib/litegraph.core.js:2504:11)
    at LGraph.configure (http://172.16.112.129:9999/lib/litegraph.core.js:2240:26)
    at LGraph.configure (http://172.16.112.129:9999/scripts/app.js:1393:22)
    at LGraph.configure (http://172.16.112.129:9999/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://172.16.112.129:9999/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:69:21)
    at ComfyApp.loadGraphData (http://172.16.112.129:9999/scripts/app.js:1838:15)
    at async app.loadGraphData (http://172.16.112.129:9999/extensions/core/undoRedo.js:25:12)
    at async app.loadGraphData (http://172.16.112.129:9999/extensions/ComfyUI-Manager/components-manager.js:771:9)
    at async app.loadGraphData (http://172.16.112.129:9999/extensions/ComfyUI-Easy-Use/js/easy/easy.js:519:20)
This may be due to the following script:
/extensions/ComfyUI-Easy-Use/js/getset.js
```
