### ISSUE TITLE
mac 'applyBrushNet' object has no attribute 'inpaint_files'

### ISSUE THREAD

**Issue by yiwangsimple** [yolain/ComfyUI-Easy-Use#217]
运行你示例的brushnet流报错，
!!! Exception during processing!!! 'applyBrushNet' object has no attribute 'inpaint_files'
Traceback (most recent call last):
  File "/Users/weiwei/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/weiwei/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/weiwei/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/weiwei/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 2125, in apply
    brushnet_model, = cls.brushnet_loading(self, brushnet, dtype)
  File "/Users/weiwei/ComfyUI/custom_nodes/ComfyUI-BrushNet/brushnet_nodes.py", line 58, in brushnet_loading
    brushnet_file = os.path.join(self.inpaint_files[brushnet], brushnet)
AttributeError: 'applyBrushNet' object has no attribute 'inpaint_files'

**Comment by whitebaby** [comment]
同样的问题，和操作系统无关，版本回退了，也是同样的问题。linux，windows下都有这个错误

**Comment by yolain** [comment]
> 同样的问题，和操作系统无关，版本回退了，也是同样的问题。linux，windows下都有这个错误

可以更到1.1.9以上。1.1.8是引用的BrushNet包的, 需要和BrushNet之前版本一致才行。
