### ISSUE TITLE
Error occurred when executing easy a1111Loader:  'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by 0002kgHg** [yolain/ComfyUI-Easy-Use#238]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[EasyUse] 正在加载模型...
!!! Exception during processing!!! 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/comfyui/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/comfyui/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/comfyui/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/comfyui/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 1041, in a1111loader
    return super().adv_pipeloader(ckpt_name, 'Default', vae_name, clip_skip,
  File "/comfyui/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 945, in adv_pipeloader
    model, clip, vae, clip_vision, lora_stack = easyCache.load_main(ckpt_name, config_name, vae_name, lora_name, lora_model_strength, lora_clip_strength, optional_lora_stack, model_override, clip_override, vae_override, prompt)
  File "/comfyui/custom_nodes/ComfyUI-Easy-Use/py/libs/loader.py", line 415, in load_main
    model, clip, vae, clip_vision = self.load_checkpoint(ckpt_name_1)
  File "/comfyui/custom_nodes/ComfyUI-Easy-Use/py/libs/loader.py", line 228, in load_checkpoint
    loaded_ckpt = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=output_clip, output_clipvision=output_clipvision, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/comfyui/comfy/sd.py", line 498, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
  File "/comfyui/comfy/utils.py", line 14, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
AttributeError: 'NoneType' object has no attribute 'lower'
![企业微信截图_1720075883717](https://github.com/yolain/ComfyUI-Easy-Use/assets/90631570/ffeebffa-e3f0-4afc-9a18-e02e8847f3a7)

**Comment by 0002kgHg** [comment]
what did i missing？

**Comment by yolain** [comment]
checkpoint not found

**Comment by yolain** [comment]
If you are not using XYInputs: Checkpoint, you don't need to add it, It interferes with the normal acquisition of models

**Comment by kane1718** [comment]
> If you are not using XYInputs: Checkpoint, you don't need to add it, It interferes with the normal acquisition of models

There is a model, the file location is correct, but the error has been reported, how to solve it
