### ISSUE TITLE
使用apply ipadapter这个节点的时候报错

### ISSUE THREAD

**Issue by klossm** [yolain/ComfyUI-Easy-Use#246]
报错内容如下，preset那里设置为 plus（high strength）

[EasyUse] easy ipadapterApply: Using ClipVisonModel CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors Cached
[EasyUse] easy ipadapterApply: Using IpAdapterModel ip-adapter-plus_sd15.safetensors Cached
!!! Exception during processing!!! 'IPAdapter' object has no attribute 'apply_ipadapter'
Traceback (most recent call last):
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3049, in apply
    model, images = cls().apply_ipadapter(model, ipadapter, image, weight, start_at, end_at, weight_type='standard', attn_mask=attn_mask)
AttributeError: 'IPAdapter' object has no attribute 'apply_ipadapter'

**Comment by frommmmmg** [comment]
我也是这个错误。。。怎么回事。。。。
