### ISSUE TITLE
powerpaint errot TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#247]
!!! Exception during processing!!! expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2564, in apply
    new_pipe, = applyPowerPaint().apply(new_pipe, image, mask, powerpaint_model, powerpaint_clip, dtype, fitting, function, scale, start_at, end_at)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2453, in apply
    ppclip, = cls.load_powerpaint_clip(base_clip, os.path.join(folder_paths.get_full_path("inpaint", powerpaint_clip)))
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 108, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by yolain** [comment]
clip缺失?

**Comment by cloudZwj** [comment]
![WX20240718-180049@2x](https://github.com/user-attachments/assets/8164b6ca-8d72-46ae-86cb-2a9c246cbdbd)
请问这两个模型文件要放在哪个目录下

**Comment by yolain** [comment]
> ![WX20240718-180049@2x](https://private-user-images.githubusercontent.com/77393822/349911352-8164b6ca-8d72-46ae-86cb-2a9c246cbdbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTEyMjAsIm5iZiI6MTcyMTMxMDkyMCwicGF0aCI6Ii83NzM5MzgyMi8zNDk5MTEzNTItODE2NGI2Y2EtOGQ3Mi00NmFlLTg2Y2ItMmE5YzI0NmNiZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzNTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMTkyN2IyN2ZjMzQ0NzU0NDMxZDY5NDgyMTE0MjgyMjBkMmYyYTE4MjUwNTdmNmM0YWViYzM1OGUzZWQ2ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PKl2qSKJY2ndD3wA5g0lODYU92FtoBwX58keErGv6Ng) 请问这两个模型文件要放在哪个目录下

models/inpaint/powerpaint

**Comment by lingchen5201314** [comment]
模型去哪里下载啊 请给个链接

**Comment by lingchen5201314** [comment]
> ![WX20240718-180049@2x](https://private-user-images.githubusercontent.com/77393822/349911352-8164b6ca-8d72-46ae-86cb-2a9c246cbdbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjYzOTgsIm5iZiI6MTcyMTk2NjA5OCwicGF0aCI6Ii83NzM5MzgyMi8zNDk5MTEzNTItODE2NGI2Y2EtOGQ3Mi00NmFlLTg2Y2ItMmE5YzI0NmNiZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAzNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOTAxOWUxODVjZjJiOTYzZTkxOTJkMjk5MjIyMDdlN2MzMTNjNDYwMjYzZmIwNTQ0NzFjNzM2NWE1ZjBlNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GCZaXhEXvyIag_AtcubNO_6r688dODeVk9OZNgg1plw) 请问这两个模型文件要放在哪个目录下

去哪下载这2个模型啊

**Comment by hanetyb** [comment]
here https://huggingface.co/JunhaoZhuang/PowerPaint-v2-1/tree/main/PowerPaint_Brushnet
