### ISSUE TITLE
PULID用不了

### ISSUE THREAD

**Issue by cardenluo** [yolain/ComfyUI-Easy-Use#250]
请问要装哪个pulid，有好几个版本，我已经装了2个版本，还是不能用Easy A Apply PuLID

**Comment by yolain** [comment]
cubiq的版本

**Comment by cardenluo** [comment]
谢谢大佬，cubiq的ComfyUI_InstantID也一起装上就可以了。
缺了InstantID的面部分析

**Comment by yolain** [comment]
> 谢谢大佬，cubiq的ComfyUI_InstantID也一起装上就可以了。 缺了InstantID的面部分析

啊？我修复下。写错了。

**Comment by cardenluo** [comment]
啊。更新后，反而用不了了

![image](https://github.com/user-attachments/assets/3a4495ea-74a8-4a54-92b9-4f7b7c5c5d5a)
Traceback (most recent call last):
  File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3736, in run
    insightface_model, = load_insightface_cls().load_insight_face(insightface)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PulidInsightFaceLoader' object has no attribute 'load_insight_face'

**Comment by yolain** [comment]
> 啊。更新后，反而用不了了
> 
> ![image](https://private-user-images.githubusercontent.com/133877069/348453199-3a4495ea-74a8-4a54-92b9-4f7b7c5c5d5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTE1NjYsIm5iZiI6MTcyMDg1MTI2NiwicGF0aCI6Ii8xMzM4NzcwNjkvMzQ4NDUzMTk5LTNhNDQ5NWVhLTc0YTgtNGE1NC05MmI5LTRmN2I3YzVjNWQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwNjE0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTViYjg2OTFmNTQ3NTY5ZThkMjQ1YTMzMjY1ZWQyNDg1MmI0MDhhNzMxYzM5NzcxZTExZWE0MmM4YmNjN2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hz6eirTR6fK-JSdq8nrRYV29noa469LtFE8dfQID3oA) Traceback (most recent call last): File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func res_value = old_func(*final_args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3736, in run insightface_model, = load_insightface_cls().load_insight_face(insightface) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'PulidInsightFaceLoader' object has no attribute 'load_insight_face'

晕了 他命名不一样。一个带下划线 一个没有。稍等下
