### ISSUE TITLE
An error is reported after the update，cannot import name 'sd2_clip' from 'comfy'

### ISSUE THREAD

**Issue by grinlau18** [yolain/ComfyUI-Easy-Use#272]
Hello author, when I fully updated comfyui, the node reported the following error when it was started again, resulting in the failure to load the easy use node after entering the operation interface.

Pls how to fix it, thanks！

Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Easy-Use/__init__.py", line 20, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
  File "/root/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 1661, in <module>
    from .dynamiCrafter import DynamiCrafter
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/dynamiCrafter/__init__.py", line 11, in <module>
    from .utils.model_utils import DynamiCrafterBase, DYNAMICRAFTER_CONFIG, load_image_proj_dict, load_dynamicrafter_dict, get_image_proj_model
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/dynamiCrafter/utils/model_utils.py", line 10, in <module>
    from comfy import sd2_clip
ImportError: cannot import name 'sd2_clip' from 'comfy' (unknown location)

Cannot import /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Easy-Use module for custom nodes: cannot import name 'sd2_clip' from 'comfy' (unknown location)

**Comment by luze1011** [comment]
I also encountered the same problem

**Comment by luze1011** [comment]
I tried reinstalling the Comfy module, but to no avail

**Comment by gisu** [comment]
Same here. Tested with a fresh ComfyUI Installation, Easy Use import failed

**Comment by bruibbruib** [comment]
Same here.
Temp fix, (that may break things???):
copy 'sd2_clip.py' from 'encoders' folder, to 'comfy' folder, one level up.
mine is working now.
godd luck!

**Comment by alexnikospb** [comment]
Yes, I have the same problem, Easy Use import failed

**Comment by AlUlkesh** [comment]
It's this change in ComfyUI that caused this:
https://github.com/comfyanonymous/ComfyUI/commit/4ba7fa0244badcf901f2b8ddbfb8539c6398672f

This PR should fix that...

**Comment by aurelienLavanchy** [comment]
> Same here. Temp fix, (that may break things???): copy 'sd2_clip.py' from 'encoders' folder, to 'comfy' folder, one level up. mine is working now. good luck!

Rather than copying the file, you can make a symbolic link while we wait for a fix

**Comment by moddz** [comment]
same issue

**Comment by kawaii2020** [comment]
+1  pls fix it.  
thannnnnnk you!

**Comment by yolain** [comment]
> It's this change in ComfyUI that caused this: [comfyanonymous/ComfyUI@4ba7fa0](https://github.com/comfyanonymous/ComfyUI/commit/4ba7fa0244badcf901f2b8ddbfb8539c6398672f)
> 
> This PR should fix that...

❤️ Thanks to fixed it. It's the weekend and I've only just seen this issue.

**Comment by AugmentedRealityCat** [comment]
I had to uninstall ComfyUI-Easy-Use and reinstall it to fix the problem by the way. Simply using the "try to fix the problem" from the Manager's interface was not enough in my case.

**Comment by Walfy-sjl** [comment]
just adjust some code, like below, it works for me. (just like the link show)
https://github.com/comfyanonymous/ComfyUI/commit/4ba7fa0244badcf901f2b8ddbfb8539c6398672f

from comfy import sd2_clip
from comfy.text_encoders import sd2_clip

**Comment by anseltrust** [comment]
Is there a solution for this, still not working.

**Comment by scofano** [comment]
Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-saveimagewithmetadata module for custom nodes: No module named 'comfy.sd2_clip'

Fresh install April/2025

**Comment by AlUlkesh** [comment]
> > Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-saveimagewithmetadata module for custom nodes: No module named 'comfy.sd2_clip'
> > Fresh install April/2025
> 
> same,did you fix it?

I'm afraid you're posting this in the wrong place. Try here: https://github.com/nkchocoai/ComfyUI-SaveImageWithMetaData

**Comment by tieungao79** [comment]
> > Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-saveimagewithmetadata module for custom nodes: No module named 'comfy.sd2_clip'
> > Fresh install April/2025
> 
> same,did you fix it?

I just got same issue at fixed it at my local. Will make an PR at ComfyUI-SaveImageWithMetaData repo latter if you can't wait I can share what I did.
