### ISSUE TITLE
秋叶整合包安装报错试过多种解决途径

### ISSUE THREAD

**Issue by laochendeai** [yolain/ComfyUI-Easy-Use#278]
![easyuse1](https://github.com/user-attachments/assets/7de00af0-1268-47c0-934f-e6597163445b)
(url)
我的日志文件[
[Diagnostics-1722322579.log](https://github.com/user-attachments/files/16423768/Diagnostics-1722322579.log)
](url)

ComfyUI Launcher Diagnostic File

Date: 2024-07-30 14:56:24
Launcher Version: 2.8.5.349
Data File Version: 2024-07-27 13:21
ComfyUI Version: 55f37baae85a5f3ef6d87743445fcce1f0477ba9 (2024-03-07 14:49:20)
Working Directory: E:\ComfyUI-aki-v1.3
------------------------
System Information: 
OS: Microsoft Windows NT 10.0.19044.0
CPU: 16 cores
Memory Size: 32768 MB
Page File Size: 2048 MB

NVIDIA Management Library:
  NVIDIA Driver Version: 546.33
  NVIDIA Management Library Version: 12.546.33

CUDA Driver:
  Version: 12030
  Devices: 
    00000000:01:00.0 0: NVIDIA GeForce RTX 4060 [89] 7 GB

NvApi:
  Version: 54633 r545_00

HIP Driver:
  Not Available

DirectML Driver: 
  Devices: 
    10370 0: NVIDIA GeForce RTX 4060 7 GB
    10370 1: NVIDIA GeForce RTX 4060 7 GB

Intel Level Zero Driver:
  Not Available

------------------------
Environment Variables: 
Path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Eclipse Adoptium\jdk-17.0.8.7-hotspot\bin;C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Git\bin;E:\ComfyUI-aki-v1.3;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;d:\Program Files\JetBrains\PyCharm Community Edition 2022.2\bin;;C:\src\flutter\bin;D:\ollama;D:\newtonai\ollama-openwebui\ollama;C:\Users\Administrator\AppData\Local\Programs\Ollama
USERDOMAIN_ROAMINGPROFILE=PC-20230706SWPO
PROCESSOR_ARCHITECTURE=AMD64
TMP=C:\Users\ADMINI~1\AppData\Local\Temp
DriverData=C:\Windows\System32\Drivers\DriverData
CommonProgramW6432=C:\Program Files\Common Files
CM2014DIR=C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\
LOCALAPPDATA=C:\Users\Administrator\AppData\Local
SESSIONNAME=Console
USERNAME=Administrator
ILBDIR=C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\
OS=Windows_NT
ALLUSERSPROFILE=C:\ProgramData
ProgramData=C:\ProgramData
windir=C:\Windows
APPDATA=C:\Users\Administrator\AppData\Roaming
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
PROCESSOR_LEVEL=6
HF_ENDPOINT=https://hf-mirror.com
JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.8.7-hotspot
NUMBER_OF_PROCESSORS=16
PyCharm Community Edition=d:\Program Files\JetBrains\PyCharm Community Edition 2022.2\bin;
HOMEPATH=\Users\Administrator
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
ComSpec=C:\Windows\system32\cmd.exe
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
ProgramFiles(x86)=C:\Program Files (x86)
USERDOMAIN=PC-20230706SWPO
SystemRoot=C:\Windows
PUBLIC=C:\Users\Public
ProgramW6432=C:\Program Files
ProgramFiles=C:\Program Files
ss-root=C:\Program Files (x86)\senseshield\ss
FPS_BROWSER_USER_PROFILE_STRING=Default
USERPROFILE=C:\Users\Administrator
PROCESSOR_REVISION=bf02
LOGONSERVER=\\PC-20230706SWPO
HOMEDRIVE=C:
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
COMPUTERNAME=PC-20230706SWPO
OLLAMA_BASE_URL=http://127.0.0.1:11434
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 191 Stepping 2, GenuineIntel
SystemDrive=C:
OLLAMA_MODELS=D:/newtonai/ollama-openwebui/llm_models
CommonProgramFiles=C:\Program Files\Common Files
------------------------
Paths: 
Python: E:\ComfyUI-aki-v1.3\python\python.exe
  - Python Paths:
    - E:\ComfyUI-aki-v1.3\python\DLLs
    - E:\ComfyUI-aki-v1.3\python\lib
    - E:\ComfyUI-aki-v1.3\python
    - E:\ComfyUI-aki-v1.3\python\lib\site-packages
    - E:\ComfyUI-aki-v1.3\python\lib\site-packages\win32
    - E:\ComfyUI-aki-v1.3\python\lib\site-packages\win32\lib
    - E:\ComfyUI-aki-v1.3\python\lib\site-packages\Pythonwin
  - Python Packages:
    - absl_py 2.0.0 
    - accelerate 0.33.0 
    - addict 2.4.0 
    - aiohttp 3.8.5 
    - aiosignal 1.3.1 
    - albumentations 1.3.1 
    - annotated_types 0.7.0 
    - antlr4_python3_runtime 4.9.3 
    - anyio 4.2.0 
    - argostranslate 1.9.1 
    - async_timeout 4.0.3 
    - attrs 23.1.0 
    - beautifulsoup4 4.12.2 
    - boltons 23.0.0 
    - boto3 1.34.149 
    - botocore 1.34.149 
    - certifi 2024.7.4 
    - cffi 1.16.0 
    - chardet 5.2.0 
    - charset_normalizer 3.3.2 
    - click 8.1.7 
    - clip_interrogator 0.6.0 
    - cmake 3.27.7 
    - colorama 0.4.6 
    - coloredlogs 15.0.1 
    - colorlog 6.8.0 
    - compel 2.0.3 
    - contourpy 1.1.1 
    - cssselect2 0.7.0 
    - ctranslate2 3.20.0 
    - cycler 0.12.1 
    - Cython 3.0.8 
    - deepdiff 6.7.1 
    - deep_translator 1.11.4 
    - diffusers 0.25.0 
    - einops 0.6.1 
    - embreex 2.17.7.post4 
    - exceptiongroup 1.2.0 
    - fairscale 0.4.13 
    - filelock 3.15.4 
    - flatbuffers 23.5.26 
    - fonttools 4.43.1 
    - frozenlist 1.4.0 
    - fsspec 2024.6.1 
    - ftfy 6.1.1 
    - gitdb 4.0.11 
    - GitPython 3.1.40 
    - h11 0.14.0 
    - h2 4.1.0 
    - hpack 4.0.0 
    - httpcore 1.0.2 
    - httpx 0.26.0 
    - huggingface_hub 0.23.4 
    - humanfriendly 10.0 
    - hyperframe 6.0.1 
    - idna 3.7 
    - imageio 2.31.5 
    - importlib_metadata 6.8.0 
    - insightface 0.7.3 
    - Jinja2 3.1.2 
    - jmespath 1.0.1 
    - joblib 1.3.2 
    - jsonschema 4.20.0 
    - jsonschema_specifications 2023.7.1 
    - kiwisolver 1.4.5 
    - kornia 0.7.1 
    - lark_parser 0.12.0 
    - lazy_loader 0.3 
    - lightning_utilities 0.11.6 
    - llvmlite 0.41.1 
    - lxml 4.9.3 
    - mapbox_earcut 1.0.1 
    - MarkupSafe 2.1.3 
    - matplotlib 3.8.0 
    - matrix_client 0.4.0 
    - mediapipe 0.10.7 
    - mpmath 1.3.0 
    - multidict 6.0.4 
    - networkx 3.1 
    - numba 0.58.1 
    - numexpr 2.8.8 
    - numpy 1.23.5 
    - omegaconf 2.3.0 
    - onnx 1.15.0 
    - onnxruntime 1.17.0 
    - onnxruntime_gpu 1.17.0 
    - opencv_contrib_python 4.8.1.78 
    - opencv_python 4.8.1.78 
    - opencv_python_headless 4.7.0.72 
    - open_clip_torch 2.24.0 
    - ordered_set 4.1.0 
    - packaging 24.1 
    - pandas 2.1.3 
    - piexif 1.1.3 
    - pilgram 1.2.1 
    - Pillow 9.5.0 
    - pip 24.2 
    - platformdirs 3.11.0 
    - pooch 1.8.0 
    - portalocker 2.8.2 
    - prettytable 3.9.0 
    - protobuf 3.20.3 
    - psutil 5.9.5 
    - pycocoevalcap 1.2 
    - pycocotools 2.0.8 
    - pycparser 2.21 
    - pydantic 2.8.2 
    - pydantic_core 2.20.1 
    - PyMatting 1.1.12 
    - pynvml 11.5.0 
    - pyparsing 3.1.1 
    - pypng 0.20220715.0 
    - pyreadline3 3.4.1 
    - python_dateutil 2.8.2 
    - pytorch_lightning 2.3.3 
    - pytz 2023.3.post1 
    - pywavelets 1.5.0 
    - pywin32 306 
    - PyYAML 6.0.1 
    - py_cpuinfo 9.0.0 
    - qrcode 7.4.2 
    - qudida 0.0.4 
    - referencing 0.30.2 
    - regex 2023.8.8 
    - rembg 2.0.52 
    - reportlab 4.0.6 
    - requests 2.32.3 
    - rpds_py 0.12.0 
    - Rtree 1.1.0 
    - s3transfer 0.10.2 
    - safetensors 0.4.2 
    - scikit_image 0.20.0 
    - scikit_learn 1.3.2 
    - scipy 1.12.0 
    - seaborn 0.13.0 
    - segment_anything 1.0 
    - sentencepiece 0.1.99 
    - setuptools 65.5.0 
    - shapely 2.0.2 
    - simpleeval 0.9.13 
    - six 1.16.0 
    - smmap 5.0.1 
    - sniffio 1.3.0 
    - sounddevice 0.4.6 
    - soupsieve 2.5 
    - spandrel 0.3.4 
    - stanza 1.1.1 
    - svg.path 6.3 
    - sympy 1.12 
    - tabulate 0.9.0 
    - termcolor 2.3.0 
    - thop 0.1.1.post2209072238 
    - threadpoolctl 3.2.0 
    - tifffile 2023.9.26 
    - timm 0.6.13 
    - tinycss2 1.2.1 
    - tokenizers 0.15.2 
    - tomli 2.0.1 
    - torch 2.1.2+cu118 
    - torchmetrics 1.4.0.post0 
    - torchsde 0.2.5 
    - torchvision 0.16.2+cu118 
    - tqdm 4.66.4 
    - trampoline 0.1.2 
    - transformers 4.38.2 
    - trimesh 4.0.9 
    - typing_extensions 4.12.2 
    - tzdata 2023.3 
    - ultralytics 8.0.223 
    - urllib3 2.2.2 
    - vhacdx 0.0.5 
    - wcwidth 0.2.8 
    - webencodings 0.5.1 
    - xformers 0.0.23.post1+cu118 
    - xxhash 3.4.1 
    - yacs 0.1.8 
    - yapf 0.40.2 
    - yarl 1.9.2 
    - zipp 3.17.0 
    - cstr 0.1.0 
    - easydict 1.11 
    - ffmpy 0.3.0 
    - fvcore 0.1.5.post20221221 
    - googletrans_py 4.0.0 
    - img2texture 1.0.6 
    - iopath 0.1.10 
    - pycollada 0.8 
    - sacremoses 0.0.53 
    - svglib 1.5.1 
Git: E:\ComfyUI-aki-v1.3\git\cmd\git.exe
Shell: C:\Windows\system32\cmd.exe
Cache Path: E:\ComfyUI-aki-v1.3\.cache
------------------------
Engine Validator: 
PyTorch: 2.1.2+cu118 C(11080)___
OnnxRuntime: CUDA(11080)
------------------------
Port Info: 
Exclusion List:
  Non-administered:
    
  Administered:
    50000..60
In Use (v4):
  135 => 1260
  139 => 4
  139 => 4
  445 => 4
  1027 => 2868
  1045 => 900
  4301 => 7096
  4310 => 7096
  4709 => 2728
  5040 => 8264
  5283 => 7096
  8188 => 7380
  9210 => 7096
  12668 => 11548
  22223 => 3268
  49664 => 976
  49665 => 744
  49666 => 1784
  49667 => 1872
  49668 => 3756
In Use (v6):
  135 => 1260
  445 => 4
  1027 => 2868
  1045 => 900
  22223 => 3268
  49664 => 976
  49665 => 744
  49666 => 1784
  49667 => 1872
  49668 => 3756
------------------------
Config: 
Audience Type: 新手
Engine: CUDA GPU 0: NVIDIA GeForce RTX 4060 (8 GB) [0]
VRAM Optimization: Auto [Auto]
Port: 8188 [8188]
XAttn Optimization: Xformers [Xformers]
Upcast Attention: True [True]
Precision: Auto [Auto]
Text Encoder Precision: Auto [Auto]
UNet Precision: Auto [Auto]
VAE Precision: Auto [Auto]
Preview Method: Auto [Auto]
Smart Memory: True [True]
Deterministic: False [False]
Listen: False [False]
Server Name:  []
HF Offline Mode: False [False]
Cuda Allocator Backend: CudaMallocAsync [CudaMallocAsync]
Prevent Sysmem Fallback: False
Extra Args: 
------------------------
Network Preferences: 
Proxy Address: 
Proxy Git: False
Proxy Pip: False
Proxy Model Download: False
Proxy Env: False
Mirror Pypi: False
Mirror Git: False
Mirror ExtensionList: False
Mirror Huggingface: False
Github Acceleration: False
------------------------
Log: 
** ComfyUI startup time: 2024-07-30 14:52:17.852869
** Platform: Windows

** Python version: 
3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable:
 E:\ComfyUI-aki-v1.3\python\python.exe
** Log path:
 E:\ComfyUI-aki-v1.3\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds:
 E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold

   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 32605 MB
xformers version: 0.0.23.post1+cu118

Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync

VAE dtype: 
torch.bfloat16
Using xformers cross attention
[AnimateDiff] - [0;33mWARNING[0m - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
Adding E:\ComfyUI-aki-v1.3\custom_nodes
 to sys.path

[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m
Loaded Efficiency nodes from E:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet

Loaded AnimateDiff from 
E:\ComfyUI-aki-v1.3\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Loaded IPAdapter nodes from E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus
'NoneType' object is not callable
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V4.83.2)
Loaded ImpactPack nodes from E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Crystools [0;32mINFO[0m] Crystools version: 1.11.0
[Crystools [0;32mINFO[0m] CPU: 13th Gen Intel(R) Core(TM) i5-13490F - Arch: AMD64 - OS: Windows 10
[Crystools [0;32mINFO[0m] GPU/s:
[Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 4060
[Crystools [0;32mINFO[0m] NVIDIA Driver: 546.33
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 20, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
  File "E:\ComfyUI-aki-v1.3\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 5, in <module>
    import comfy.utils, comfy.sample, comfy.samplers, comfy.controlnet, comfy.model_base, comfy.model_management, comfy.sampler_helpers, comfy.supported_models
ModuleNotFoundError: No module named 'comfy.sampler_helpers'

Cannot import E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use module for custom nodes: No module named 'comfy.sampler_helpers'

### Loading: ComfyUI-Inspire-Pack (V0.65.6)
[Impact Pack] Wildcards loading done.

### Loading: Workspace Manager (V1.0.0)
------------------------------------------
[34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki

------------------------------------------

[1;35m### [START] ComfyUI AlekPet Nodes ###[0m
[92mNode -> ArgosTranslateNode [Loading][0m
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[92mNode -> DeepTranslatorNode [Loading][0m
[92mNode -> ExtrasNode [Loading][0m
[92mNode -> GoogleTranslateNode [Loading][0m
[92mNode -> PainterNode [Loading][0m
[92mNode -> PoseNode [Loading][0m
[1;35m### [END] ComfyUI AlekPet Nodes ###[0m
[34mFizzleDorf Custom Nodes: [92mLoaded[0m
Patching UNetModel.forward
UNetModel.forward has been successfully patched.
[1;32m[Power Noise Suite]: 🦚🦚🦚 [93m[3mwark![0m 🦚🦚🦚
[1;32m[Power Noise Suite]:[0m Tamed [93m11[0m wild nodes.

Import times for custom nodes:
   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds:
 E:\ComfyUI-aki-v1.3\custom_nodes\style_aligned_comfy
   0.0 seconds:
 E:\ComfyUI-aki-v1.3\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds:
 E:\ComfyUI-aki-v1.3\custom_nodes\FreeU_Advanced

   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\sdxl_prompt_styler
   0.0 seconds:
 E:\ComfyUI-aki-v1.3\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\cg-use-everywhere

   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Eagle-PNGInfo

   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux

   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_experiments

   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\PowerNoiseSuite

   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\images-grid-comfy-plugin

   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\comfyui-animatediff
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet

   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Custom-Scripts

   0.0 seconds:
 E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\comfyui-workspace-manager
   0.0 seconds:
 E:\ComfyUI-aki-v1.3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds:
 E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_smZNodes

   0.1 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold

   0.2 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_FizzNodes
   0.2 seconds (IMPORT FAILED):
 E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use
   0.3 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager

   1.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantID

   1.2 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\comfyui-art-venture
   4.3 seconds: 
E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Crystools

   5.8 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
FETCH DATA from: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json
------------------------
Fault Traceback: 
Not Available

**Comment by laochendeai** [comment]
我已经解决报错的问题了。我的解决步骤是
1。执行pip install numpy>=1.19.0
2.更新秋叶整合包内核。在更新的 过程中出现了错误。

3.我重新执行了pip install -r requirements.txt
命令。重启了绘世管理器。目前看插件是安装好了
