### ISSUE TITLE
error in load node

### ISSUE THREAD

**Issue by metercai** [yolain/ComfyUI-Easy-Use#281]
[Comfyd] [ERROR] An error occurred while retrieving information for the 'easy pixArtLoader' node.
[Comfyd] Traceback (most recent call last):
  File "/home/ubuntu/llmlab/drawing/comfy/server.py", line 443, in get_object_info
    out[x] = node_info(x)
  File "/home/ubuntu/llmlab/drawing/comfy/server.py", line 420, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/ubuntu/llmlab/drawing/comfy/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 1941, in INPUT_TYPES
    devices.append(f"cuda:{k}")
NameError: name 'devices' is not defined

"devices" only once in "ComfyUI-Easy-Use/py/easyNodes.py"

**Comment by yolain** [comment]
Hey guy! I didn't have this issue, maybe you're using a previous version. I currently only have support for t5xxl from sd3 clip on pixartloader. 
<img width="1114" alt="截屏2024-08-01 12 59 51" src="https://github.com/user-attachments/assets/609a89b8-2e6b-4442-bd2b-8c0dd6c9bef4">
