### ISSUE TITLE
ComfyUI 升级到 262 后 easy use 无法加载

### ISSUE THREAD

**Issue by guhuajun** [yolain/ComfyUI-Easy-Use#290]
如题，看样子是 Comfy 的变化引起的

```
ComfyUI: 262[ea03c9](2024-08-02)
Manager: V2.46.3
```

```bash
Traceback (most recent call last):
2024-08-03T05:12:56.392759589Z   File "/root/ComfyUI/nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
2024-08-03T05:12:56.392770079Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-08-03T05:12:56.392775236Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-08-03T05:12:56.392780353Z   File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/__init__.py", line 20, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03T05:12:56.392818477Z   File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
2024-08-03T05:12:56.392823424Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-08-03T05:12:56.392828321Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03T05:12:56.392833150Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-08-03T05:12:56.392848203Z   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-08-03T05:12:56.392853294Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 1611, in <module>
    from .dynamiCrafter import DynamiCrafter
  File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/dynamiCrafter/__init__.py", line 11, in <module>
2024-08-03T05:12:56.392878433Z     from .utils.model_utils import DynamiCrafterBase, DYNAMICRAFTER_CONFIG, load_image_proj_dict, load_dynamicrafter_dict, get_image_proj_model
  File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/dynamiCrafter/utils/model_utils.py", line 10, in <module>
2024-08-03T05:12:56.392888787Z     from comfy import sd2_clip
ImportError: cannot import name 'sd2_clip' from 'comfy' (unknown location)
2024-08-03T05:12:56.392904799Z 
Cannot import /root/ComfyUI/custom_nodes/ComfyUI-Easy-Use module for custom nodes: cannot import name 'sd2_clip' from 'comfy' (unknown location)
```

**Comment by yolain** [comment]
easy 也要升

**Comment by yolain** [comment]
报什么？

**Comment by guhuajun** [comment]
> 我的comfyui升级到了2024-8-4这个节点就掉了，要求的环境不一样了！

删了在重新安装 easy use试试，我的问题已经解决，所以先 close issue 了。
