### ISSUE TITLE
使用 embedding 报错

### ISSUE THREAD

**Issue by Hileowill** [yolain/ComfyUI-Easy-Use#299]
Traceback (most recent call last):
  File "D:\Program Files\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Program Files\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Program Files\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Program Files\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 1073, in comfyloader
    return super().adv_pipeloader(ckpt_name, 'Default', vae_name, clip_skip,
  File "D:\Program Files\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 938, in adv_pipeloader
    negative_embeddings_final, negative_wildcard_prompt, model, clip = prompt_to_cond('negative', model, clip, clip_skip, lora_stack, negative, negative_token_normalization, negative_weight_interpretation, a1111_prompt_style, my_unique_id, prompt, easyCache, model_type=model_type)
  File "D:\Program Files\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\conditioning.py", line 20, in prompt_to_cond
    text = zh_to_en([text])[0]
  File "D:\Program Files\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\translate.py", line 230, in zh_to_en
    result = parser.parse(t).children
  File "D:\Anaconda3\envs\comfyui2\lib\site-packages\lark\lark.py", line 581, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "D:\Anaconda3\envs\comfyui2\lib\site-packages\lark\parser_frontends.py", line 106, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "D:\Anaconda3\envs\comfyui2\lib\site-packages\lark\parsers\lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "D:\Anaconda3\envs\comfyui2\lib\site-packages\lark\parsers\lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "D:\Anaconda3\envs\comfyui2\lib\site-packages\lark\parsers\lalr_parser.py", line 188, in parse_from_state
    raise e
  File "D:\Anaconda3\envs\comfyui2\lib\site-packages\lark\parsers\lalr_parser.py", line 179, in parse_from_state
    state.feed_token(token)
  File "D:\Anaconda3\envs\comfyui2\lib\site-packages\lark\parsers\lalr_parser.py", line 129, in feed_token
    raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
lark.exceptions.UnexpectedToken: Unexpected token Token('COLON', ':') at line 1, column 30.
Expected one of:
        * COMMA
        * $END

**Comment by yolain** [comment]
提词 发我看看。

**Comment by Hileowill** [comment]
![微信截图_20240811090117](https://github.com/user-attachments/assets/a07caff1-a72a-43c7-abce-755b3f6ba7fd)

**Comment by Hileowill** [comment]
Realistic, DSLR, RAW photo, Portrait photography, 1990s_(style),by Wong Kar-wai

(High angle shot:1.2), from below， Chiaroscuro, Rambrandt Lighting, From below, (F1.2:1.2), 100mm lens

A charming woman, black wavy long hair, dark turtleneck sweater, sitting in a saloon, cup of wine on the table


text, watermark, nsfw, embedding:[SDXL]_[写实]_negativeXL,
