### ISSUE TITLE
easy ksampler 报错 求助，comfyui和easyuse都更新到最新版本了

### ISSUE THREAD

**Issue by LiGe-In** [yolain/ComfyUI-Easy-Use#304]
!!! Exception during processing!!! 0
Traceback (most recent call last):
  File "/home/work/comfyui/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/work/comfyui/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/work/comfyui/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/work/comfyui/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5338, in simple
    return super().run(pipe, None, None, None, None, None, image_output, link_id, save_prefix,
  File "/home/work/comfyui/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5307, in run
    return process_sample_state(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, start_step, last_step, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, force_full_denoise, disable_noise, samp_custom)
  File "/home/work/comfyui/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5091, in process_sample_state
    samp_samples = sampler.common_ksampler(samp_model, samp_seed, steps, cfg, sampler_name, scheduler, samp_positive, samp_negative, samp_samples, denoise=denoise, preview_latent=preview_latent, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, disable_noise=disable_noise)
  File "/home/work/comfyui/custom_nodes/ComfyUI-Easy-Use/py/libs/sampler.py", line 116, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative,
  File "/home/work/comfyui/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control_reference.py", line 47, in refcn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/home/work/comfyui/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/work/comfyui/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/work/comfyui/custom_nodes/ComfyUI-Easy-Use/py/brushnet/model_patch.py", line 106, in modified_sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/work/comfyui/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/work/comfyui/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/work/comfyui/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/work/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/work/comfyui/comfy/k_diffusion/sampling.py", line 600, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/work/comfyui/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/work/comfyui/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/work/comfyui/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/work/comfyui/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/work/comfyui/comfy/samplers.py", line 202, in calc_cond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
  File "/home/work/comfyui/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 536, in get_control_inject
    return self.get_control_advanced(x_noisy, t, cond, batched_number)
  File "/home/work/comfyui/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control.py", line 32, in get_control_advanced
    return self.sliding_get_control(x_noisy, t, cond, batched_number)
  File "/home/work/comfyui/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control.py", line 79, in sliding_get_control
    return self.control_merge(None, control, control_prev, output_dtype)
  File "/home/work/comfyui/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 643, in control_merge_inject
    x = control_output[i]
KeyError: 0

**Comment by ultimatech-cn** [comment]
Meet the error almost same. I am trying to upgrade all the related node. 
The following is error message

> Error occurred when executing easy kSampler:

'NoneType' object has no attribute 'shape'

File "E:\training\ComfyUI\execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\training\ComfyUI\execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\training\ComfyUI\execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "E:\training\ComfyUI\execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\training\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 5392, in simple
return super().run(pipe, None, None, None, None, None, image_output, link_id, save_prefix,
