### ISSUE TITLE
Cannot import \ComfyUI\custom_nodes\ComfyUI-Easy-Use module for custom nodes: 'STABILITY_API_DEFAULT'`

### ISSUE THREAD

**Issue by falcon204** [yolain/ComfyUI-Easy-Use#338]
Started since I did a ComfyUi update. I tried the reinstall, uninstall with no effects. Same issue. 

`Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 21, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 7549, in <module>
    from .libs.stability import stableAPI
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\stability.py", line 155, in <module>
    stableAPI = StabilityAPI()
                ^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\stability.py", line 22, in __init__
    self.getAPIKeys()
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\stability.py", line 48, in getAPIKeys
    self.api_current = data['STABILITY_API_DEFAULT']
                       ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'STABILITY_API_DEFAULT'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use module for custom nodes: 'STABILITY_API_DEFAULT'`

**Comment by yolain** [comment]
Does your comfyUI folder not have write access to the file

**Comment by falcon204** [comment]
Yep I even tried to remove the access then reenabling access. Still same error since updating comfUi
 
![Screenshot 2024-08-21 192710](https://github.com/user-attachments/assets/d879b81d-887f-48fc-b150-687511da8176)

**Comment by falcon204** [comment]
Ok it's working now. I removed access then reenabled access to the folder. Then in manager I uninstalled the [ComfyUI Easy Use] then reinstalled . Fixed. So weird how update messed it all up with no system changes 🤷‍♂️
