### ISSUE TITLE
KeyError: None using loader comfy

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#37]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2084, in adv_pipeloader
    return fullLoader.adv_pipeloader(self, ckpt_name, 'Default', vae_name, clip_skip,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 1905, in adv_pipeloader
    inputs_positive_values = prompt[my_unique_id]['inputs']['positive'] if "positive" in prompt[my_unique_id]['inputs'] else None
                                                                                         ~~~~~~^^^^^^^^^^^^^^
KeyError: None

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/ed6ad882-d80d-4bc7-97df-32090649449d)

**Comment by yolain** [comment]
晚点我修复一下。

**Comment by kohongying** [comment]
> 晚点我修复一下。

遇到相同的问题，求修复

**Comment by yolain** [comment]
> > 晚点我修复一下。
> 
> 
> 
> 遇到相同的问题，求修复

已修复了
