### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by pepebc** [yolain/ComfyUI-Easy-Use#373]
![error](https://github.com/user-attachments/assets/23c16e28-6539-4c8b-98f0-48879425004e)

Traceback (most recent call last):
  File "/media/DATOS/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/media/DATOS/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/media/DATOS/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/media/DATOS/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/media/DATOS/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 2565, in apply
    base_clip = get_local_filepath(model_url, os.path.join(folder_paths.models_dir, 'clip'))
  File "/media/DATOS/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/libs/utils.py", line 224, in get_local_filepath
    raise Exception(f'无法从 {url} 下载，错误信息：{str(err.args[0])}')
IndexError: tuple index out of range

**Comment by wusev1e** [comment]
models/clip folder missing “model.fp16.safetensors”.This is how I solved it.

**Comment by pepebc** [comment]
> models/clip folder missing “model.fp16.safetensors”.This is how I solved it.

Correct, I forgot to put the model. Thanks

**Comment by Mxx2848283** [comment]
如果comfyui返回此报错，在python或者Java中怎么捕获并给出返回提示
