### ISSUE TITLE
styles目录路径拼接报错

### ISSUE THREAD

**Issue by cybercall** [yolain/ComfyUI-Easy-Use#38]
```
[ERROR] An error occurred while retrieving information for the 'easy stylesSelector' node.
Traceback (most recent call last):
  File "/data/codes/opensource/ai/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/data/codes/opensource/ai/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/codes/opensource/ai/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 1358, in INPUT_TYPES
    for file_name in os.listdir(os.path.join(__file__, "../../styles")):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/data/codes/opensource/ai/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py/../../styles'
```

路径拼接报错，改成 `os.path.join(Path(__file__).parent.parent, 'styles')` 这种形式正常。

```
diff --git a/py/easyNodes.py b/py/easyNodes.py
index fb99733..e9c1632 100644
--- a/py/easyNodes.py
+++ b/py/easyNodes.py
@@ -1355,8 +1355,9 @@ class stylesPromptSelector:
     @classmethod
     def INPUT_TYPES(s):
         styles = ["fooocus_styles"]
-        for file_name in os.listdir(os.path.join(__file__, "../../styles")):
-            file = os.path.join(__file__, "../../styles", file_name)
+
+        for file_name in os.listdir(os.path.join(Path(__file__).parent.parent, 'styles')):
+            file = os.path.join(Path(__file__).parent.parent, "styles", file_name)
             if os.path.isfile(file) and file_name.endswith(".json") and "styles" in file_name.split(".")[0]:
                 styles.append(file_name.split(".")[0])
```

**Comment by yolain** [comment]
804be24b12914a779e9078ccef2d7bd319d98cb7 已兼容
