### ISSUE TITLE
KeyError: 'lora_name'

### ISSUE THREAD

**Issue by woshilhz001** [yolain/ComfyUI-Easy-Use#39]
![屏幕截图 2024-01-21 112818](https://github.com/yolain/ComfyUI-Easy-Use/assets/21053332/08a54c11-61e5-4c09-8dd9-81b59cbe3882)

[EasyUse] pipeIn[49]: Clip missing from pipeLine
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3295, in run
    return process_xyPlot(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, xyPlot)
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3203, in process_xyPlot
    "lora_name": pipe["loader_settings"]["lora_name"],
KeyError: 'lora_name'

**Comment by yolain** [comment]
804be24b12914a779e9078ccef2d7bd319d98cb7 调了。

**Comment by woshilhz001** [comment]
![屏幕截图 2024-01-22 131713](https://github.com/yolain/ComfyUI-Easy-Use/assets/21053332/cca2b8da-7d45-4bf2-ad69-9ac2545df74c)


ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ai\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 4829, in xy_value
    values = "; ".join(values)
TypeError: sequence item 0: expected str instance, tuple found
