### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 's'

### ISSUE THREAD

**Issue by keno-log** [yolain/ComfyUI-Easy-Use#405]
Node: For Loop End
Issue details
![Uploading brave_screenshot.png…]()

got prompt
!!! Exception during processing!!! invalid literal for int() with base 10: 's'
Traceback (most recent call last):
  File "E:\ComfyUI_AIR\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_AIR\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_AIR\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_AIR\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 813, in for_loop_end
    start_node = next((x for x in all_nodes if x['id'] == int(while_open)), None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_AIR\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 813, in <genexpr>
    start_node = next((x for x in all_nodes if x['id'] == int(while_open)), None)
                                                          ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 's'

**Comment by yolain** [comment]
Please re-uploading your screenshot.

**Comment by heshengtao** [comment]
![1730775780713](https://github.com/user-attachments/assets/811c1068-525e-43f1-880a-9df8ba4da1ad)
大佬，我也遇到了这个问题，请问，是我没有连对吗

got prompt
!!! Exception during processing!!! invalid literal for int() with base 10: 's'
Traceback (most recent call last):
  File "E:\GitHub\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 842, in for_loop_end
    start_node = next((x for x in all_nodes if x['id'] == int(while_open)), None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 842, in <genexpr>
    start_node = next((x for x in all_nodes if x['id'] == int(while_open)), None)
                                                          ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 's'

Prompt executed in 0.01 seconds

**Comment by heshengtao** [comment]
好像是comfyui版本过低的原因哈哈哈
