### ISSUE TITLE
imagesplitimage node issue

### ISSUE THREAD

**Issue by g558800** [yolain/ComfyUI-Easy-Use#406]
!!! Exception during processing !!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "H:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\AI\ComfyUI\nodes.py", line 1499, in save_images
    full_output_folder, filename, counter, subfolder, filename_prefix = folder_paths.get_save_image_path(filename_prefix, self.output_dir, images[0].shape[1], images[0].shape[0])
TypeError: 'NoneType' object is not subscriptable

![image](https://github.com/user-attachments/assets/11a93641-359a-481e-8037-aaa3969c0624)

**Comment by yolain** [comment]
Check if there are more than one images in the input port images

**Comment by g558800** [comment]
only one image.

**Comment by yolain** [comment]
> only one image.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/fd247808-15bb-44c6-95c4-8e35c08cb259)
> 
> 
> 
> 

This is the node that splits from the image batch into multiple images. I think you might be needing imagesplitgird.
