### ISSUE TITLE
人体Segmention 三个方法都报错

### ISSUE THREAD

**Issue by flybirdxx** [yolain/ComfyUI-Easy-Use#412]
![image](https://github.com/user-attachments/assets/1e52d90b-4b9c-4e10-8ddc-d47cc67374b7)
后台错误大概如下:
Prompt executed in 0.05 seconds
got prompt
!!! Exception during processing !!! invalid literal for int() with base 10: 'Upper-clothes'
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use\py\image.py", line 1126, in parsing
    mask_components = list(map(int, mask_components))
ValueError: invalid literal for int() with base 10: 'Upper-clothes'

乱神能看看这个问题吗

**Comment by yolain** [comment]
版本问题吧

**Comment by flybirdxx** [comment]
> 版本问题吧

我comfyui和EU插件全都是最新版的,刚更新

**Comment by yolain** [comment]
重新创建下这个节点然后再连接看看。

**Comment by flybirdxx** [comment]
> 重新创建下这个节点然后再连接看看。

我把EU前端插件重新构建了下,现在没问题了,感谢乱神的解答
