### ISSUE TITLE
 ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'

### ISSUE THREAD

**Issue by samen168** [yolain/ComfyUI-Easy-Use#423]
# ComfyUI Error Report
## Error Details
- **Node Type:** easy kolorsLoader
- **Exception Type:** TypeError
- **Exception Message:** ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'
## Stack Trace
```
  File "H:\sd\comfy-torch-2.1.2+cu118\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "H:\sd\comfy-torch-2.1.2+cu118\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 1882, in adv_pipeloader
    positive_embeddings_final = chatglm3_adv_text_encode(chatglm3_model, positive, auto_clean_gpu)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\custom_nodes\ComfyUI-Easy-Use\py\kolors\text_encode.py", line 92, in chatglm3_adv_text_encode
    cond = chatglm3_text_encode(chatglm3_model, text, clean_gpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\custom_nodes\ComfyUI-Easy-Use\py\kolors\text_encode.py", line 33, in chatglm3_text_encode
    text_inputs = tokenizer(
                  ^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\.ext\Lib\site-packages\transformers\tokenization_utils_base.py", line 3016, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\.ext\Lib\site-packages\transformers\tokenization_utils_base.py", line 3126, in _call_one
    return self.encode_plus(
           ^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\.ext\Lib\site-packages\transformers\tokenization_utils_base.py", line 3202, in encode_plus
    return self._encode_plus(
           ^^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\.ext\Lib\site-packages\transformers\tokenization_utils.py", line 801, in _encode_plus
    return self.prepare_for_model(
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\.ext\Lib\site-packages\transformers\tokenization_utils_base.py", line 3698, in prepare_for_model
    encoded_inputs = self.pad(
                     ^^^^^^^^^

  File "H:\sd\comfy-torch-2.1.2+cu118\.ext\Lib\site-packages\transformers\tokenization_utils_base.py", line 3500, in pad
    encoded_inputs = self._pad(
                     ^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-94-g614377a
- **Arguments:** H:\sd\comfy-torch-2.1.2+cu118\main.py --auto-launch --preview-method auto --disable-smart-memory --disable-cuda-malloc --output-directory H:\sd-output\sd-comfyui\output
- **OS:** nt
- **Python Version:** 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.2+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12877955072
  - **VRAM Free:** 4560503804
  - **Torch VRAM Total:** 7012876288
  - **Torch VRAM Free:** 12829692

## Logs
```
2024-10-10 13:50:05,384 - root - INFO - Total VRAM 12281 MB, total RAM 32578 MB
2024-10-10 13:50:05,385 - root - INFO - pytorch version: 2.1.2+cu118
2024-10-10 13:50:05,846 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-10-10 13:50:05,846 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-10 13:50:05,847 - root - INFO - Disabling smart memory management
2024-10-10 13:50:05,847 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
2024-10-10 13:50:08,007 - root - INFO - Using xformers cross attention
2024-10-10 13:50:09,343 - root - INFO - [Prompt Server] web root: H:\sd\comfy-torch-2.1.2+cu118\web
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path checkpoints H:/sd/stable-diffusion\models/Stable-diffusion
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path clip H:/sd/stable-diffusion\models/clip/
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path clip_vision H:/sd/stable-diffusion\models/clip_vision/
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path configs H:/sd/stable-diffusion\models/Stable-diffusion
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path vae H:/sd/stable-diffusion\models/VAE
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path loras H:/sd/stable-diffusion\models/Lora
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path loras H:/sd/stable-diffusion\models/LyCORIS
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path upscale_models H:/sd/stable-diffusion\models/ESRGAN
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path upscale_models H:/sd/stable-diffusion\models/RealESRGAN
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path upscale_models H:/sd/stable-diffusion\models/SwinIR
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path embeddings H:/sd/stable-diffusion\models/embeddings
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path hypernetworks H:/sd/stable-diffusion\models/hypernetworks
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path controlnet H:/sd/stable-diffusion\models/ControlNet
2024-10-10 13:50:09,346 - root - INFO - Adding extra search path ipadapter H:/sd/stable-diffusion\models/ipadapter
2024-10-10 13:50:27,490 - root - INFO - Total VRAM 12281 MB, total RAM 32578 MB
2024-10-10 13:50:27,490 - root - INFO - pytorch version: 2.1.2+cu118
2024-10-10 13:50:27,490 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-10-10 13:50:27,490 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-10 13:50:27,490 - root - INFO - Disabling smart memory management
2024-10-10 13:50:27,490 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
2024-10-10 13:50:28,435 - root - WARNING - Traceback (most recent call last):
  File "H:\sd\comfy-torch-2.1.2+cu118\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\sd\comfy-torch-2.1.2+cu118\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

2024-10-10 13:50:28,435 - root - WARNING - Cannot import H:\sd\comfy-torch-2.1.2+cu118\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by samen168** [comment]
transformers  4.45.2 >> 4.43.4 
worked
