### ISSUE TITLE
Error after ComfyUI 0.2.3 update

### ISSUE THREAD

**Issue by jonny7737** [yolain/ComfyUI-Easy-Use#427]
[ERROR] An error occurred while retrieving information for the 'easy XYPlotAdvanced' node.
Traceback (most recent call last):
  File "/Users/xxx/ComfyUI/server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/Users/xxx/ComfyUI/server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 7349, in INPUT_TYPES
    if s.user_font_dir:
       ^^^^^^^^^^^^^^^
AttributeError: type object 'pipeXYPlotAdvanced' has no attribute 'user_font_dir'

Good luck.

**Comment by jonny7737** [comment]
Fix confirmed.

**Comment by jonny7737** [comment]
Update the node

**Comment by Guoqiang17** [comment]
Update the node ComfyUI Easy Use
