### ISSUE TITLE
使用xy plot会导致controlnet被覆盖吗

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#43]
突然发现好像接上这个 controlnet控制就失效了

**Comment by whmc76** [comment]
[装备升级测试版.json](https://github.com/yolain/ComfyUI-Easy-Use/files/14071772/default.json)

我尝试使用controlnet去控制姿势，另外使用xy去批量替换提示词的权重，但是无论是openpose还是depth看起来都失效了，没有使用xy的时候他们是正常的

**Comment by yolain** [comment]
是的。因为XY这边替换了提示词 就相当于重新使用提示词编码了正反向条件，XYPlot它最终逻辑都是在采样器那边做处理的。我试试如果和pipe里正向在做一次拼接是否可行。

**Comment by whmc76** [comment]
好的 我有想到是这个原因，所以尝试x使用关键词替换，y加入了一个只有1个条件的controlnet，但是会报错。。。

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_test\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3338, in run
    return samplerFull.run(self, pipe, None, None,None,None,None, image_output, link_id, save_prefix,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3302, in run
    return process_xyPlot(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, xyPlot)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3250, in process_xyPlot
    latents_plot = sampleXYplot.get_labels_and_sample(plot_image_vars, latent_image, preview_latent, start_step,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 937, in get_labels_and_sample
    self.image_list, self.max_width, self.max_height, self.latents_plot = self.sample_plot_image(
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 806, in sample_plot_image
    _pipe, = controlnetAdvanced().controlnetApply(_pipe, image, control_net_name, None, strength, start_percent,
    ^^^^^^
ValueError: too many values to unpack (expected 1)

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/9c434b4d-4d24-4a91-80b8-f82799f7b016)

**Comment by yolain** [comment]
失敬了🤣哥，你这个id 我之前都没认出来，记得最早接触comfy的时候就看的你的视频

**Comment by yolain** [comment]
和pipe的拼接是不行的，只能在y轴也使用cn才可以，上面那个报错我解决了，等下个版本我更新下。不过如果需要多个controlnet控制的话，可能我这边还需要再补个xy输入 的controlnet_stack

**Comment by whmc76** [comment]
> 失敬了🤣哥，你这个id 我之前都没认出来，记得最早接触comfy的时候就看的你的视频

啊不不 你们这些开发者才是社区核心 我现在做啥都用easy use 治好了多年的强迫症 所以一直追着你提需求哈哈哈

**Comment by whmc76** [comment]
另外不知道是不是插件装太多了 最近总感觉崩溃的情况很多，而且很多时候显存不会自动释放 跑着跑着就一直顶头满占用了，要是有个看显存占比还能手动释放的东西就妙了

**Comment by yolain** [comment]
> 另外不知道是不是插件装太多了 最近总感觉崩溃的情况很多，而且很多时候显存不会自动释放 跑着跑着就一直顶头满占用了，要是有个看显存占比还能手动释放的东西就妙了

其实我的建议这些都不太适合跟随comfy启动，看着挺方便的，其实还蛮占用的，真还不如三方软件或者系统操作，而且启动comfy时间也变慢了，假设它调用读取系统数值的某个依赖需要0.5秒，如果n个包有这个依赖，启动时间是n*0.5。 对了，还有个点我和你说下，我看你前面那个工作流，因为我这边开发的逻辑是 xyplot 在presampling后的，可能放在之前会报错。

**Comment by whmc76** [comment]
> > 另外不知道是不是插件装太多了 最近总感觉崩溃的情况很多，而且很多时候显存不会自动释放 跑着跑着就一直顶头满占用了，要是有个看显存占比还能手动释放的东西就妙了
> 
> 其实我的建议这些都不太适合跟随comfy启动，看着挺方便的，其实还蛮占用的，真还不如三方软件或者系统操作，而且启动comfy时间也变慢了，假设它调用读取系统数值的某个依赖需要0.5秒，如果n个包有这个依赖，启动时间是n*0.5。 对了，还有个点我和你说下，我看你前面那个工作流，因为我这边开发的逻辑是 xyplot 在presampling后的，可能放在之前会报错。

好的了解了 这个真的是隐藏属性了。。
