### ISSUE TITLE
kolors节点ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'

### ISSUE THREAD

**Issue by liulsg** [yolain/ComfyUI-Easy-Use#434]
!!! Exception during processing !!! ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'
Traceback (most recent call last):
  File "G:\AI\ComfyUI_w\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\AI\ComfyUI_w\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 1882, in adv_pipeloader
    positive_embeddings_final = chatglm3_adv_text_encode(chatglm3_model, positive, auto_clean_gpu)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\kolors\text_encode.py", line 92, in chatglm3_adv_text_encode
    cond = chatglm3_text_encode(chatglm3_model, text, clean_gpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\kolors\text_encode.py", line 33, in chatglm3_text_encode
    text_inputs = tokenizer(
                  ^^^^^^^^^^
  File "G:\AI\ComfyUI_w\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3016, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3126, in _call_one
    return self.encode_plus(
           ^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3202, in encode_plus
    return self._encode_plus(
           ^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\python_embeded\Lib\site-packages\transformers\tokenization_utils.py", line 801, in _encode_plus
    return self.prepare_for_model(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_w\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3698, in prepare_for_model
    encoded_inputs = self.pad(
                     ^^^^^^^^^
  File "G:\AI\ComfyUI_w\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3500, in pad
    encoded_inputs = self._pad(
                     ^^^^^^^^^^
TypeError: ChatGLMTokenizer._pad() got an unexpected keyword argument 'padding_side'

**Comment by liulsg** [comment]
已经解决
