### ISSUE TITLE
UnboundLocalError: local variable 'files_list' referenced before assignment

### ISSUE THREAD

**Issue by metercai** [yolain/ComfyUI-Easy-Use#497]
[Comfyd] [ERROR] An error occurred while retrieving information for the 'easy XYPlotAdvanced' node.
[Comfyd] Traceback (most recent call last):
  File "/home/ubuntu/llmlab/drawing/SimpleSDXL/comfy/server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "/home/ubuntu/llmlab/drawing/SimpleSDXL/comfy/server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/ubuntu/llmlab/drawing/SimpleSDXL/comfy/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 7365, in INPUT_TYPES
    "font": (["None"] + files_list,)
UnboundLocalError: local variable 'files_list' referenced before assignment

**Comment by metercai** [comment]
line 7350:
flies_list = []
change to :
files_list = []
