### ISSUE TITLE
XYPlotAdvanced - UnboundLocalError: local variable 'files_list' referenced before assignment

### ISSUE THREAD

**Issue by DasWookie** [yolain/ComfyUI-Easy-Use#509]
I'm seeing another error being emitted into the console log. I'm not utilizing the XYPlotAdvanced node, but when I start an image generation this is being emitted to the console:
```
[ERROR] An error occurred while retrieving information for the 'easy XYPlotAdvanced' node.
Traceback (most recent call last):
  File "/home/cyber/ComfyUI/server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "/home/cyber/ComfyUI/server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/cyber/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 7366, in INPUT_TYPES
    "font": (["None"] + files_list,)
UnboundLocalError: local variable 'files_list' referenced before assignment

```

**Comment by yolain** [comment]
Linux?

**Comment by DasWookie** [comment]
Yes
