### ISSUE TITLE
Missing wildcards directory.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [yolain/ComfyUI-Easy-Use#517]
A commit in the last 24 hrs seems to have broken this repo. Due to an error that was appearing after updating, I deleted the repo and cloned it again. Now it gives this error on startup:

```
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 34, in <module>
    with open(example_path, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Easy-Use\\wildcards\\example.txt'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use module for custom nodes: [Errno 2] No such file or directory: 'E:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Easy-Use\\wildcards\\example.txt'
```

**Comment by GalaxyTimeMachine** [comment]
UPDATE: I manually added the missing directory and an empty example.txt, but it is now showing the original error that caused me to reinstall the repo:

```
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 66, in <module>
    json.dump(data, f, indent=4, ensure_ascii=False)
  File "json\__init__.py", line 180, in dump
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-4: character maps to <undefined>

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use module for custom nodes: 'charmap' codec can't encode characters in position 1-4: character maps to <undefined>
```

**Comment by meikodunois** [comment]
I have the exact same problem 🙉 I hope they fix it soon 🐵

**Comment by Kwintessen** [comment]
For anyone on windows that comes here with issues importing because of the error:
 `UnicodeEncodeError: 'charmap' codec can't encode...maps to <undefined>`
At least with errors that reference: `File "encodings\cp1252.py"` or some variant of that in their traceback.

On mine, I had to patch  the [read_wildcard_dict](https://github.com/yolain/ComfyUI-Easy-Use/blob/main/py/libs/wildcards.py) function in wildcard.py, so that `.yaml` files would be opened with UTF-8 encoding, because the encoding issues were caused by `yaml.load(f, Loader=yaml.FullLoader` having some kind of issue with Windows.

```
            elif file.endswith('.yaml'):
                file_path = os.path.join(root, file)
                with open(file_path, 'r') as f:           # <--------- THE LINE THAT CAUSED MY ISSUE
                    yaml_data = yaml.load(f, Loader=yaml.FullLoader)

```
I changed ` with open(file_path, 'r') as f:` 
to 
`with open(file_path, 'r', encoding="UTF-8") as f:`
