### ISSUE TITLE
Error since November 8 update.

### ISSUE THREAD

**Issue by Neytiri7** [yolain/ComfyUI-Easy-Use#518]
```
Traceback (most recent call last):
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 66, in <module>
    json.dump(data, f, indent=4, ensure_ascii=False)
  File "json\__init__.py", line 180, in dump
UnicodeEncodeError: 'cp949' codec can't encode character '\u6837' in position 3: illegal multibyte sequence
```

**Comment by yolain** [comment]
1c82506ab962cb17103e6e954519fd20593d9446 Fixed, try updating to see if it resolves.
