### ISSUE TITLE
[ERROR] An error occurred while retrieving information for the 'easy mochiLoader' node.

### ISSUE THREAD

**Issue by aaronkingdom** [yolain/ComfyUI-Easy-Use#530]
[ERROR] An error occurred while retrieving information for the 'easy mochiLoader' node.
Traceback (most recent call last):
  File "E:\AI\ComfyUI\ComfyUI\server.py", line 486, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\server.py", line 454, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2113, in INPUT_TYPES
    clip = folder_paths.get_filename_list("text_encoders")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\folder_paths.py", line 242, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\folder_paths.py", line 207, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'text_encoders'

**Comment by aaronkingdom** [comment]
someone has same problem?

**Comment by sev7eny** [comment]
same+1

**Comment by aaronkingdom** [comment]
this is running log:

E:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-15 17:43:06.644043
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\AI\ComfyUI\python_embeded\python.exe
** ComfyUI Path: E:\AI\ComfyUI\ComfyUI
** Log path: E:\AI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.7 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16384 MB, total RAM 32406 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Laptop GPU : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: E:\AI\ComfyUI\ComfyUI\web
E:\AI\ComfyUI\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
sageattn not found, using sdpa
sageattn not found, using sdpa
sageattn not found, using sdpa
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3080 Laptop GPU
[Crystools INFO] NVIDIA Driver: 566.14
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
### Loading: ComfyUI-Impact-Pack (V7.11.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.6)
Total VRAM 16384 MB, total RAM 32406 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Laptop GPU : cudaMallocAsync
theUpsiders Logic Nodes: Loaded
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2652 [0c7c98a9] | Released on '2024-09-05'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available False
edit_mask.available True
## clip_interrogator_model not found: E:\AI\ComfyUI\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: E:\AI\ComfyUI\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: E:\AI\ComfyUI\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available False
MiniCPMNode.available
Scenedetect.available False
FishSpeech.available False
SenseVoice.available False
Whisper.available False
fal-client## OK
FalVideo.available
 --------------
E:\AI\ComfyUI\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.5.1+cu124
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
### [START] ComfyUI AlekPet Nodes v1.0.33 ###
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode [Loading]
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading] Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading]

Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> PoseNode: PoseNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
[comfy_mtb] | INFO -> loaded 86 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

[rgthree-comfy] Loaded 42 fantastic nodes. 🎉

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 219 nodes successfully.

        "The journey of a thousand miles begins with one step." - Lao Tzu


Import times for custom nodes:
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_bnb_nf4_fp4_Loaders
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Dimensional-Latent-Perlin
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\florence_dw
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-eesahesNodes
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-lama-remover
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-propost
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mask-util
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_MX_post_processing-nodes
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-moondream
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Florence-2
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Mira
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Studio
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-magic-clothing
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-dream-project
   0.0 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfy_mtb
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-tensorops
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.2 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.2 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   0.4 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.4 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.6 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet
   0.6 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Image-Filters
   0.7 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BiRefNet
   0.9 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\bilbox-comfyui
   1.1 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   1.5 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.5 seconds: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet





Starting server
To see the GUI go to: http://192.168.1.4:8188 or http://127.0.0.1:8188
To see the GUI go to: https://192.168.1.4:8189 or https://127.0.0.1:8189
E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
FETCH DATA from: E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
BilboX LUTs path set to: E:\AI\ComfyUI\ComfyUI\custom_nodes\bilbox-comfyui\luts
BilboX LUTs path set to: E:\AI\ComfyUI\ComfyUI\custom_nodes\bilbox-comfyui\luts
[ERROR] An error occurred while retrieving information for the 'easy mochiLoader' node.
Traceback (most recent call last):
  File "E:\AI\ComfyUI\ComfyUI\server.py", line 486, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\server.py", line 454, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2113, in INPUT_TYPES
    clip = folder_paths.get_filename_list("text_encoders")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\folder_paths.py", line 242, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\folder_paths.py", line 207, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'text_encoders'

[]
[]
E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
E:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
BilboX LUTs path set to: E:\AI\ComfyUI\ComfyUI\custom_nodes\bilbox-comfyui\luts
BilboX LUTs path set to: E:\AI\ComfyUI\ComfyUI\custom_nodes\bilbox-comfyui\luts
[ERROR] An error occurred while retrieving information for the 'easy mochiLoader' node.
Traceback (most recent call last):
  File "E:\AI\ComfyUI\ComfyUI\server.py", line 486, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\server.py", line 454, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2113, in INPUT_TYPES
    clip = folder_paths.get_filename_list("text_encoders")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\folder_paths.py", line 242, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI\folder_paths.py", line 207, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'text_encoders'

[]
[]

**Comment by GegenDenTag** [comment]
jo same

**Comment by dxdpxl** [comment]
same +1

After that error, it lists every single checkpoint and lora on my ssd incl. path, which results in a massive long error log, really annoying!

**Comment by yolain** [comment]
> same +1
> 
> 
> 
> After that error, it lists every single checkpoint and lora on my ssd incl. path, which results in a massive long error log, really annoying!

update comfyUI core or update easy use

**Comment by dxdpxl** [comment]
> update comfyUI core or update easy use

Ther error is gone, Thanks! Today morning there where no updates from Easy-Use, at least not over the manager. But I did a git pull and it updated, comfy core was up to date, BUT I updated comfy over the "update_comfyui_and_python_dependencies.bat" and there where a few updates.

I have to say that, Easy-Use is obviously not to blame for the log spam I have with the paths, I apologize! Maybe someone knows, if it is a new "feature" from comfy, that all checkpoints and loras incl. the whole path (incl. subfolders) are displayed in the terminal the moment you open/start the UI (not the run_comfy.bat) in the browser? Because right now there is no error before or after this "spam".

**Comment by GegenDenTag** [comment]
yourpath\ComfyUI_windows_portable\update\G:\KI\ComfyUI_windows_portable\update.bat works for me too, thanks.
