### ISSUE TITLE
mModule 'diffusers' load failed. If you don't have it installed, do it

### ISSUE THREAD

**Issue by aswordok** [yolain/ComfyUI-Easy-Use#548]
conda list diffusers
# packages in environment at D:\+AI\miniconda3\envs\312:
#
# Name                    Version                   Build  Channel
diffusers                 0.27.2                   pypi_0    pypi
diffusers-torch           0.18.2          py312hfc267ef_0    defaults

  D:\+AI\myComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\brushnet\model.py （匹配1次）
	行 1687:     # print("\33[33mModule 'diffusers' load failed. If you don't have it installed, do it:\033[0m")
  D:\+AI\myComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\layer_diffuse\model.py （匹配1次）
	行 386:     print("\33[33mModule 'diffusers' load failed. If you don't have it installed, do it:\033[0m")

how to do with?

**Comment by yolain** [comment]
Re-install  the higher version of diffusers.

**Comment by aswordok** [comment]
Has be solved by update to 0.31.0

conda list | findstr diffusers
	diffusers                 0.27.2                   pypi_0    pypi
	diffusers-torch           0.18.2          py312hfc267ef_0    defaults
python -m pip install -U diffusers
Successfully installed diffusers-0.31.0

**Comment by fafayqa** [comment]
I have exactly the same problem using the latest build!

[2024-12-22 19:16:31.744] pytorch version: 2.5.1+cu124
[2024-12-22 19:16:31.744] Set vram state to: NORMAL_VRAM
[2024-12-22 19:16:31.744] Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[2024-12-22 19:16:32.416] Using pytorch attention
[2024-12-22 19:16:33.292] [Prompt Server] web root: Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\web
[2024-12-22 19:16:33.872] [33mModule 'diffusers' load failed. If you don't have it installed, do it:[0m
[2024-12-22 19:16:33.873] [33mpip install diffusers[0m
[2024-12-22 19:16:34.084] [34m[ComfyUI-Easy-Use] server: [0mv1.2.6 [92mLoaded[0m
[2024-12-22 19:16:34.085] [34m[ComfyUI-Easy-Use] web root: [0mZ:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 [92mLoaded[0m
[2024-12-22 19:16:34.132] Traceback (most recent call last):
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2073, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting\nodes.py", line 9, in <module>
    from .modules.load_util import load_flux_fill_nf4, load_simple_flux_fill_nf4, load_vae
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting\modules\load_util.py", line 5, in <module>
    from .autoencoder_kl import AutoencoderKL
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting\modules\autoencoder_kl.py", line 19, in <module>
    from diffusers.configuration_utils import ConfigMixin, register_to_config
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?
