### ISSUE TITLE
如果使用Python3.12官方整合包，会导致很多工作流无法打开

### ISSUE THREAD

**Issue by LiJT** [yolain/ComfyUI-Easy-Use#578]
```
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\translate.py:188: SyntaxWarning: invalid escape sequence '\s'
  grammar = """
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\wildcards.py:171: SyntaxWarning: invalid escape sequence '\+'
  subpattern = keyword.replace('*', '.*').replace('+','\+')
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py:1731: SyntaxWarning: invalid escape sequence '\o'
  if output_path.endswith("ComfyUI/output") or output_path.endswith("ComfyUI\output"):
[ComfyUI-Easy-Use] server: v1.2.6 Loaded
[ComfyUI-Easy-Use] web root: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\helpers.py:7: FutureWarning: Importing from timm.models.helpers is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
```

如果是使用 Python 3.12 最新 Portable 整合包的情况下，第一次安装 Easy-Use 会出现上面的错误提示，然后，如果导入了大量使用 SetNode 等easyuse节点的工作流，还出现这种错误
![PixPin_2024-12-15_19-15-39](https://github.com/user-attachments/assets/464ec3af-d896-4f95-9c95-347e187282dd)

```
Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at e.onConnectionsChange (http://127.0.0.1:8188/extensions/ComfyUI-Easy-Use/assets/extensions-29B2pS6_.js:1:100022)
    at e.configure (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:29240:35)
    at LGraph2.configure (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:39063:17)
    at LGraph$1.configure (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:88029:26)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:88529:18)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/ComfyUI-Manager/components-manager.js:773:9)
    at async reader.onload (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:88898:11)
This may be due to the following script:
/extensions/ComfyUI-Easy-Use/assets/extensions-29B2pS6_.js
```

如果移除了Easy Use 节点，则工作流显示正常，显示布局如下，都是正常的
![PixPin_2024-12-15_19-15-56](https://github.com/user-attachments/assets/5893d190-9381-4c2a-93bc-9ccadb3b2fdf)

工作流地址：
https://civitai.com/models/899863

求乱乱大佬解决，这个问题会导致所有使用最新版comfyUI的人，被迫只能降低python版本，或者回去用秋叶的整合包了，秋叶的python 3.10版本的确是没有这个问题，但是未来comfyUI desktop等发展方向都是向着python 3.12发展的，我不太清楚这个问题是否与python 3.12有关，但两者最大差别也就在此了。求大佬解惑

**Comment by yolain** [comment]
下周整个3.12环境看看。 我都在用3.11的...

**Comment by LiJT** [comment]
> 下周整个3.12环境看看。 我都在用3.11的...

大佬更新的真快！确认了！此bug已经修复！
