### ISSUE TITLE
风格提示词选择器出问题了

### ISSUE THREAD

**Issue by xlibfly** [yolain/ComfyUI-Easy-Use#579]
更新内核版本后，风格提示词出问题了，看不见下面的提示词了，
Prompt executed in 1.00 seconds
got prompt
!!! Exception during processing !!! 'select_styles'
Traceback (most recent call last):
  File "F:\AI Tools\ComfyUI-aki-v1.4\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\AI Tools\ComfyUI-aki-v1.4\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\AI Tools\ComfyUI-aki-v1.4\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI Tools\ComfyUI-aki-v1.4\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\AI Tools\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 179, in run
    if prompt[my_unique_id]["inputs"]['select_styles']:
KeyError: 'select_styles'

**Comment by Universalcow** [comment]
same error

**Comment by RicharYe** [comment]
same error
