### ISSUE TITLE
"Module 'diffusers' load failed" in ComfyUI log

### ISSUE THREAD

**Issue by fafayqa** [yolain/ComfyUI-Easy-Use#587]
I am using latest ComfyUI Portable v0.3.9.10 (https://github.com/comfyanonymous/ComfyUI/releases) and have exactly the same problem using the latest build by installing from https://github.com/yolain/ComfyUI-Easy-Use.git

[2024-12-22 19:16:31.744] pytorch version: 2.5.1+cu124
[2024-12-22 19:16:31.744] Set vram state to: NORMAL_VRAM
[2024-12-22 19:16:31.744] Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[2024-12-22 19:16:32.416] Using pytorch attention
[2024-12-22 19:16:33.292] [Prompt Server] web root: Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\ComfyUI\web
[2024-12-22 19:16:33.872] �[33mModule 'diffusers' load failed. If you don't have it installed, do it:�[0m
[2024-12-22 19:16:33.873] �[33mpip install diffusers�[0m
[2024-12-22 19:16:34.084] �[34m[ComfyUI-Easy-Use] server: �[0mv1.2.6 �[92mLoaded�[0m
[2024-12-22 19:16:34.085] �[34m[ComfyUI-Easy-Use] web root: �[0mZ:_PSTART__APPS__AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 �[92mLoaded�[0m
[2024-12-22 19:16:34.132] Traceback (most recent call last):
File "Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2073, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 995, in exec_module
File "", line 488, in call_with_frames_removed
File "Z:_PSTART_APPS__AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting_init_.py", line 1, in
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
File "Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting\nodes.py", line 9, in
from .modules.load_util import load_flux_fill_nf4, load_simple_flux_fill_nf4, load_vae
File "Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting\modules\load_util.py", line 5, in
from .autoencoder_kl import AutoencoderKL
File "Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Inpainting\modules\autoencoder_kl.py", line 19, in
from diffusers.configuration_utils import ConfigMixin, register_to_config
File "Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers_init_.py", line 5, in
from .utils import (
File "Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils_init_.py", line 38, in
from .dynamic_modules_utils import get_class_from_dynamic_module
File "Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in
from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (Z:_PSTART__APPS__AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub_init_.py). Did you mean: 'hf_hub_download'?

**Comment by rungvang** [comment]
Have the same problem, happened maybe because some extension (in my case Florence2, not sure) uninstalled the newest diffusers version and install some old version of it. Just manually re-install it (Go to python_embeded folder. Type cmd in the top address bar, type python.exe -m uninstall diffusers, wait, then type the samething but with install).
