### ISSUE TITLE
cannot import name 'shard_checkpoint' from 'transformers.modeling_utils'  :(

### ISSUE THREAD

**Issue by divineblessing** [yolain/ComfyUI-Easy-Use#593]
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-28 11:17:30.613035
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: Z:\ComfyUI-aki-v1.3\python_embeded\python.exe
** ComfyUI Path: Z:\ComfyUI-aki-v1.3
** Log path: Z:\ComfyUI-aki-v1.3\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: Z:\ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy
   0.0 seconds: Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
   0.7 seconds: Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-PMRF
  13.0 seconds: Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager

Total VRAM 20479 MB, total RAM 65457 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 3080 : native
Using xformers attention
[Prompt Server] web root: Z:\ComfyUI-aki-v1.3\web
Web extensions folder found at Z:\ComfyUI-aki-v1.3\web\extensions\ComfyLiterals
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: Z:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: AMD Ryzen 9 5900X 12-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3080
[Crystools INFO] NVIDIA Driver: 551.61
Traceback (most recent call last):
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\loaders\peft.py", line 40, in <module>
    from .lora_base import _fetch_state_dict
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\loaders\lora_base.py", line 47, in <module>
    from peft.tuners.tuners_utils import BaseTunerLayer
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\peft\auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\peft\mapping.py", line 22, in <module>
    from peft.tuners.xlora.model import XLoraModel
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel, LoftQConfig, LoraRuntimeConfig
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\peft\tuners\lora\__init__.py", line 20, in <module>
    from .model import LoraModel
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\peft\tuners\lora\model.py", line 50, in <module>
    from .awq import dispatch_awq
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\peft\tuners\lora\awq.py", line 26, in <module>
    from awq.modules.linear import WQLinear_GEMM
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\awq\__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\awq\models\__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\awq\models\mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\awq\models\base.py", line 13, in <module>
    from transformers.modeling_utils import shard_checkpoint
ImportError: cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\transformers\modeling_utils.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Z:\ComfyUI-aki-v1.3\nodes.py", line 2089, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 21, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 17, in <module>
    from .layer_diffuse import LayerDiffuse, LayerMethod
  File "Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use\py\layer_diffuse\__init__.py", line 12, in <module>
    from .model import ModelPatcher, TransparentVAEDecoder, calculate_weight_adjust_channel
  File "Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use\py\layer_diffuse\model.py", line 23, in <module>
    from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\models\unets\__init__.py", line 6, in <module>
    from .unet_2d import UNet2DModel
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d.py", line 24, in <module>
    from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 36, in <module>
    from ..transformers.dual_transformer_2d import DualTransformer2DModel
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\models\transformers\__init__.py", line 6, in <module>
    from .cogvideox_transformer_3d import CogVideoXTransformer3DModel
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\models\transformers\cogvideox_transformer_3d.py", line 22, in <module>
    from ...loaders import PeftAdapterMixin
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback):
cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\transformers\modeling_utils.py)

Cannot import Z:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use module for custom nodes: Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback):
cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (Z:\ComfyUI-aki-v1.3\python_embeded\Lib\site-packages\transformers\modeling_utils.py)

**Comment by yangyiyu11** [comment]
I had the same problem.

**Comment by divineblessing** [comment]
> I had the same problem.

:(

**Comment by yangyiyu11** [comment]
> > I had the same problem.
> 
> :(

owner回复了我的issue，并已解决，请参看：https://github.com/yolain/ComfyUI-Easy-Use/issues/610

**Comment by divineblessing** [comment]
> > > I had the same problem.
> > 
> > 
> > :(
> 
> The owner replied to my issue and it has been solved. Please see:#610

我都忘记我要做什么要用到了，不过我也按照你的方法升级了那个插件，谢谢啦。: )
