### ISSUE TITLE
layerdiffusion presamlper 无法使用去除背景结点生成的图像

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#72]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2128, in settings
    samples = {"samples": vae.encode(image)}
                          ^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\sd.py", line 317, in encode
    samples[x:x+batch_number] = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\ldm\models\autoencoder.py", line 181, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 520, in forward
    h = self.conv_in(x)
        ^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\ops.py", line 60, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 4, 2992, 2712] to have 3 channels, but got 4 channels instead

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/b06e46f3-614e-48dd-a8eb-083025376929)

**Comment by yolain** [comment]
哪里不对吧。我测试的工作流是都ok 的， 你对照看看

**Comment by whmc76** [comment]
> 哪里不对吧。我测试的工作流是都ok 的， 你对照看看

我看过了 你是使用LD生成的图做前景，我想用现有的图片扣掉背景之后做输入，但是你得presampler结点输入要求 have 3 channels，但是我试了几个移除背景的工具都得到一样的结果，因为官方流程里透明图是转换成latent输入的就没这个问题，你看看能不能兼容一下哈哈，这真的很有用

**Comment by whmc76** [comment]
> 哪里不对吧。我测试的工作流是都ok 的， 你对照看看

我发现好像是和stableSR有冲突，禁用之后就正常了
