### ISSUE TITLE
layer_diffusion error TypeError: InpaintWorker.calculate_weight_patched() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#74]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/5ab5d86c-410d-4402-8657-ddae40989679)

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2789, in run
    result = samplerFull().run(pipe, None, None,None,None,None, image_output, link_id, save_prefix,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2686, in run
    return process_sample_state(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, start_step, last_step, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, force_full_denoise, disable_noise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2496, in process_sample_state
    samp_samples = sampler.common_ksampler(samp_model, samp_seed, steps, cfg, sampler_name, scheduler, samp_positive, samp_negative, samp_samples, denoise=denoise, preview_latent=preview_latent, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, disable_noise=disable_noise)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\sampler.py", line 83, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 248, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\sample.py", line 86, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, model.memory_required([noise_shape[0] * 2] + list(noise_shape[1:])) + inference_memory)
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\model_management.py", line 434, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\model_management.py", line 301, in model_load
    raise e
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\model_management.py", line 297, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\comfy\model_patcher.py", line 204, in patch_model
    out_weight = self.calculate_weight(self.patches[key], temp_weight, key).to(weight.dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\layer_diffusion.py", line 321, in calculate_weight
    weight = func(self, patches, weight, key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\layer_diffusion.py", line 321, in calculate_weight
    weight = func(self, patches, weight, key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\layer_diffusion.py", line 321, in calculate_weight
    weight = func(self, patches, weight, key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
TypeError: InpaintWorker.calculate_weight_patched() takes 4 positional arguments but 5 were given

**Comment by whmc76** [comment]
这很奇怪 因为第一次是可以正常运行作图的，但是再次运行就完全无法继续了

**Comment by whmc76** [comment]
这个看起来确实是和inpaint有点冲突，我屏蔽了一个用到lama和fooocus inpaint的部分跑就没事，打开跑一遍直接报废

**Comment by yolain** [comment]
底层我不太懂，我感觉可能是 定义ModelPatcher 计算权重的那块，Inpaint好像也有类似的逻辑

**Comment by whmc76** [comment]
求大佬解决一下这个问题吧，最近sdxl inpaint用的多了每天都因为这个问题重启一百多次，同时使用lora ipadapter 再进行fooocus inpaint 基本画两张图就会崩溃出现这个问题

**Comment by whmc76** [comment]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3966, in run
    return samplerFull().run(new_pipe, None, None,None,None,None, image_output, link_id, save_prefix,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3675, in run
    return process_sample_state(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, start_step, last_step, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, force_full_denoise, disable_noise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3490, in process_sample_state
    samp_samples = sampler.common_ksampler(samp_model, samp_seed, steps, cfg, sampler_name, scheduler, samp_positive, samp_negative, samples, denoise=denoise, preview_latent=preview_latent, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, disable_noise=disable_noise)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\sampler.py", line 83, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\Comfyui-StableSR\nodes.py", line 69, in hook_sample
    return original_sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 267, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_reference.py", line 46, in refcn_sample
    return orig_comfy_sample(model, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\comfy\sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\comfy\sample.py", line 86, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, model.memory_required([noise_shape[0] * 2] + list(noise_shape[1:])) + inference_memory)
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\comfy\model_management.py", line 445, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\comfy\model_management.py", line 304, in model_load
    raise e
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\comfy\model_management.py", line 300, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to, patch_weights=load_weights)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\comfy\model_patcher.py", line 247, in patch_model
    self.patch_weight_to_device(key, device_to)
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\comfy\model_patcher.py", line 228, in patch_weight_to_device
    out_weight = self.calculate_weight(self.patches[key], temp_weight, key).to(weight.dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\fooocus.py", line 64, in calculate_weight_patched
    return self.original_calculate_weight(self, remaining, weight, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InpaintWorker.calculate_weight_patched() takes 4 positional arguments but 5 were given

**Comment by yolain** [comment]
> 求大佬解决一下这个问题吧，最近sdxl inpaint用的多了每天都因为这个问题重启一百多次，同时使用lora ipadapter 再进行fooocus inpaint 基本画两张图就会崩溃出现这个问题

你没使用 layerDiffusion也会报吗

**Comment by whmc76** [comment]
> > 求大佬解决一下这个问题吧，最近sdxl inpaint用的多了每天都因为这个问题重启一百多次，同时使用lora ipadapter 再进行fooocus inpaint 基本画两张图就会崩溃出现这个问题
> 
> 你没使用 layerDiffusion也会报吗

没有，这是最难顶的，为了这个我还特意重新部署的comfyui环境，只安装了必要的几个插件，运行还是会有问题
因为目前阶段layer diffusion的出图质量还不是特别nice，实际上很少用得到，但是fooocus inpaint就很常用了
如果只是用其他功能都没什么问题，只要用到sdxl inpaint就会频繁报错，并且显存很容易爆炸（当然这个可能是其他问题

**Comment by whmc76** [comment]
因为我使用comfyui自带的原生结点去跑完全相同的流程是没有任何问题的，所以我感觉应该还是哪里的冲突可以排查一下

**Comment by yolain** [comment]
你把流程发我看看呢。 冲突的原因应该就是 fooocus改变了 modelPatcher 计算权重导致的， 可能是流程中也有其他包的node 同样使用了这个方法 calculate_weight_patched， 比如 原版的comfyui_layerdiffuse 它默认就会改变modelpatcher

**Comment by whmc76** [comment]
[重绘XL.json](https://github.com/yolain/ComfyUI-Easy-Use/files/14835114/XL.json)

**Comment by whmc76** [comment]
> 貌似不加lora 就不会。 晕。我直接用lighting模型 不加lora 就正常

不加lora也会有 但是会晚一些出现，不过lora也是很重要的，大佬fix一下吧 球球了

**Comment by yolain** [comment]
> > 貌似不加lora 就不会。 晕。我直接用lighting模型 不加lora 就正常
> 
> 不加lora也会有 但是会晚一些出现，不过lora也是很重要的，大佬fix一下吧 球球了

有难度啊，能fix我肯定早解决好了， 你试下 走原版那个 fooocus inpaint看看 有没有问题。 comfyui-inpaint-nodes
