### ISSUE TITLE
loaders error when using lora model for both 1.5 or XL

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#99]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/12de7820-71de-473f-9ede-90903c4d68cd)

[EasyUse] 正在处理模型...
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
[EasyUse] Load LORA: FilmVelvia3.safetensors: 1.0, 1.0, LBW=None, A=None, B=None
[EasyUse] 正在处理正面提示词...
[EasyUse] easy wildcards: positive: 1girl
[EasyUse] 正在处理正面提示词编码...
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 763, in adv_pipeloader
    positive_embeddings_final, positive_wildcard_prompt, model, clip = prompt_to_cond('positive', model, clip, clip_skip, pipe_lora_stack, positive, positive_token_normalization, positive_weight_interpretation, a1111_prompt_style, my_unique_id, prompt, easyCache)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\conditioning.py", line 23, in prompt_to_cond
    return (advanced_encode(clipped, text, prompt_token_normalization,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\adv_encode.py", line 315, in advanced_encode
    embeddings_final, pooled = advanced_encode_from_tokens(tokenized['l'],
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\adv_encode.py", line 200, in advanced_encode_from_tokens
    weighted_emb, pooled_base = encode_func(weighted_tokens)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\adv_encode.py", line 318, in <lambda>
    lambda x: (clip.encode_from_tokens({'l': x}), None),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\sd.py", line 135, in encode_from_tokens
    self.load_model()
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\sd.py", line 155, in load_model
    model_management.load_model_gpu(self.patcher)
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\model_management.py", line 442, in load_model_gpu
    return load_models_gpu([model])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\model_management.py", line 436, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\model_management.py", line 303, in model_load
    raise e
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\model_management.py", line 299, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to, patch_weights=load_weights)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\model_patcher.py", line 235, in patch_model
    self.patch_weight_to_device(key, device_to)
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\model_patcher.py", line 216, in patch_weight_to_device
    out_weight = self.calculate_weight(self.patches[key], temp_weight, key).to(weight.dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\fooocus.py", line 64, in calculate_weight_patched
    return self.original_calculate_weight(self, remaining, weight, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InpaintWorker.calculate_weight_patched() takes 4 positional arguments but 5 were given

**Comment by yolain** [comment]
你这应该是卡 inpaint 跟 layerDiffuse  冲突了。重启下应该就好了，那两玩意会冲突，暂时没想到好的办法。
